server:
  port: 8084

spring:
  application:
    name: haust-im-service
  redis:
    port: ${haust.redis.port:6379}
    host: ${haust.redis.host:localhost}
    password: ${haust.redis.password:}
    connect-timeout: ${haust.redis.timeout:200ms}
  rabbitmq:
    port: ${haust.rabbitmq.port:5672}
    host: ${haust.rabbitmq.host:localhost}
    password: ${haust.rabbitmq.password:guest}
    virtual-host: ${haust.rabbitmq.virtual-host:/}
    username: ${haust.rabbitmq.username:guest}

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Knife4j
knife4j:
  enable: true
