server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  datasource:
    driver-class-name: ${haust.datasource.driver-class-name}
    url: jdbc:mysql://${haust.datasource.host}:${haust.datasource.port}/${haust.datasource.database}
    username: ${haust.datasource.username}
    password: ${haust.datasource.password}
  redis:
    port: ${haust.redis.port}
    host: ${haust.redis.host}
    password: ${haust.redis.password}
    connect-timeout: ${haust.redis.timeout}
knife4j:
  enable: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haust.domain.po
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  return-page-info: check
  params: count=countSql
jwt:
  expiration-time:  288000000 #1000ms
  secret-key: 21413253453535342434324