server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: haust-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service Routes
        - id: user-service
          uri: lb://haust-user-service
          predicates:
            - Path=/user/**,/admin/login
          filters:
            - StripPrefix=0
        
        # Referral Service Routes  
        - id: referral-service
          uri: lb://haust-referral-service
          predicates:
            - Path=/user/addInfo,/user/modify,/user/page,/user/delete/**,/user/myInfo,/admin/page,/admin/permit
          filters:
            - StripPrefix=0
        
        # Forum Service Routes
        - id: forum-service
          uri: lb://haust-forum-service
          predicates:
            - Path=/user/posts/**,/user/replies/**,/admin/replies/**
          filters:
            - StripPrefix=0
        
        # IM Service Routes
        - id: im-service
          uri: lb://haust-im-service
          predicates:
            - Path=/im/**
          filters:
            - StripPrefix=0
