haust:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: your_mysql_host
    port: 3306
    database: your_database_name
    username: your_username
    password: your_password
  redis:
    port: 6379
    host: your_redis_host
    password: your_redis_password
    timeout: 200ms
  rabbitmq:
    port: 5672
    host: your_rabbitmq_host
    username: guest
    password: guest
    virtual-host: /